### ISSUE TITLE
Unable to run Docker instance

### ISSUE THREAD

**Issue by jxom** [silius-rs/silius#312]
I am attempting to run the Docker command in the README, however, I am encountering an `Init mdbx failed: 95` error.

**Reproduction:** 

```
> docker run --env RUST_BACKTRACE=1 -v ./bundler-spec-tests/keys/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266:/data/silius/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 -v ./.local/db:/data/silius/db ghcr.io/silius-rs/silius:latest node --eth-client-address http://host.docker.internal:8545 --datadir data/silius --mnemonic-file data/silius/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --beneficiary 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --entry-points 0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789 --http --http.addr 0.0.0.0 --http.port 3000 --http.api eth,debug,web3 --ws --ws.addr 0.0.0.0 --ws.port 3001 --ws.api eth,debug,web3 --eth-client-proxy-address http://host.docker.internal:8545

2024-06-04T07:50:56.958206Z  INFO silius::bundler: Starting uopool gRPC service...
2024-06-04T07:50:56.989407Z  INFO silius::bundler: UoPool component connected to Ethereum execution client with version anvil/v0.2.0
thread '<unnamed>' panicked at bin/silius/src/bundler.rs:253:74:
Init mdbx failed: 95

Location:
    /app/crates/mempool/src/database/env.rs:89:19
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::expect
   4: silius::bundler::launch_bundler::{{closure}}
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
   6: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   7: silius::utils::run_until_ctrl_c::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Vid201** [comment]
@jxom Thanks for reporting the issue. Not sure what could be wrong - works on my side

Can you please provide more information:
1. Which OS and version are you using?
2. This could be related to some permissions for database file. Can you please remove `-v ./.local/db:/data/silius/db` and try again?

**Comment by jxom** [comment]
1. MacOS 14.4
2. Tried removing that, but issue persists.

**Comment by Vid201** [comment]
Hey @jxom . I pushed a new way to build docker images. Can you please try again?

**Comment by jxom** [comment]
Issue seems to persist for me.

**Comment by Vid201** [comment]
> Issue seems to persist for me.

Just a sanity check - did the docker download the new latest docker image ( sha256:7c7f419ce38c2749284065282a7f5d6382e2450b3ca7c0a59dab7b23b161255b )?

If yes, then can you share more information about your environment (PC, chip)?

**Comment by jxom** [comment]
Ah yep, latest docker image worked. All good! thank you!
